"""add email_otp table and user profile fields

Revision ID: 159b99c22872
Revises: 5a37abab0ca1
Create Date: 2026-05-06 12:03:36.579457+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '159b99c22872'
down_revision: str | None = '5a37abab0ca1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otp_email'), 'email_otp', ['email'], unique=False)
    gender_enum = sa.Enum('hombre', 'mujer', 'no_binario', 'prefiero_no_decirlo', 'otro', name='gender_enum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('hombre', 'mujer', 'no_binario', 'prefiero_no_decirlo', 'otro', name='gender_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    sa.Enum(name='gender_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_email_otp_email'), table_name='email_otp')
    op.drop_table('email_otp')
    # ### end Alembic commands ###
