"""initial schema

Revision ID: 379c3241c147
Revises:
Create Date: 2026-05-05 09:19:56.233612+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID
from sqlalchemy.dialects import postgresql

revision: str = '379c3241c147'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('moving_time_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('descent_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_speed_mps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('avg_cadence', sa.Integer(), nullable=True),
    sa.Column('avg_power', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('start_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash', name='uq_activities_user_hash')
    )
    op.create_index('idx_activities_user_started', 'activities', ['user_id', 'started_at'], unique=False)
    op.create_index('idx_activities_start_point', 'activities', ['start_point'], unique=False, postgresql_using='gist')
    op.create_index('idx_activities_bbox', 'activities', ['bbox'], unique=False, postgresql_using='gist')
    op.create_table('laps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'lap_index', name='uq_laps_activity_index')
    )
    op.create_table('records',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('cadence', sa.SmallInteger(), nullable=True),
    sa.Column('power', sa.SmallInteger(), nullable=True),
    sa.Column('temperature', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'ts')
    )
    op.create_index('idx_records_position', 'records', ['position'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_position', table_name='records', postgresql_using='gist')
    op.drop_table('records')
    op.drop_table('laps')
    op.drop_index('idx_activities_bbox', table_name='activities', postgresql_using='gist')
    op.drop_index('idx_activities_start_point', table_name='activities', postgresql_using='gist')
    op.drop_index('idx_activities_user_started', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
